#! /usr/bin/env node

console.log('This script populates a some test books, authors, genres and bookinstances to your database. Specified database as argument - e.g.: populatedb mongodb://your_username:your_password@your_dabase_url');

//Get arguments passed on command line
var userArgs = process.argv.slice(2);
if (!userArgs[0].startsWith('mongodb://')) {
    console.log('ERROR: You need to specify a valid mongodb URL as the first argument');
    return
}

var async = require('async')
var User = require('./models/users')


var mongoose = require('mongoose');
var mongoDB = userArgs[0];
mongoose.connect(mongoDB);
var db = mongoose.connection;
mongoose.connection.on('error', console.error.bind(console, 'MongoDB connection error:'));

var users = []

function userCreate(username, password, email){
  userdetail = {username: username, password: password, email: email};
  var user = new User(userdetail);


  user.save(function(err){
    if(err){
      return
    }
    console.log('New User: ' + user);
    users.push(user);
  });
}

function createUsers(){
  async.parallel([
    function(callback){
      userCreate('user1', 'user1', 'aaa');
    },
    function(callback){
      userCreate('user2', 'user2', 'bbb');
    },
    function(callback){
      userCreate('user3', 'user3', 'ccc');
    },
    function(callback){
      userCreate('user4', 'user4', 'ddd');
    }]);
}


async.series([
    createUsers
],
// optional callback
function(err, results) {
    if (err) {
        console.log('FINAL ERR: '+err);
    }
    else {
        console.log('Users: '+users);
        
    }
    //All done, disconnect from database
    mongoose.connection.close();
});



